name = "in30days-landing"
license = "MIT"
licenselink = "https://github.com/in30days/in30days/blob/main/LICENSE"
description = "Landing page theme for in30days.org"
homepage = "https://in30days.org"
min_version = "0.112.0"

[author]
  name = "in30days"
  homepage = "https://in30days.org"
