baseURL = "https://learn.ravichaganti.com/"
languageCode = "en-us"
title = "Learn - Master Any Technology"
theme = "learn-landing"

[params]
  description = "Interactive learning paths to master programming languages and technologies"
  author = "rchaganti"
  siteName = "Learn"
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[build]
  writeStats = true
